### ISSUE TITLE
utils.cpp:372:15: error: ‘numeric_limits’ is not a member of ‘std’

### ISSUE THREAD

**Issue by Greentes2** [IEDMS/standard-bkt#3]
Hi.

I've got this error after a git clone and make all. Why not #include<limits> in utils.h? It seems to solve the issue. http://en.cppreference.com/w/cpp/types/numeric_limits

**Comment by myudelson** [comment]
Excellent point, I've been compiling using Xcode at some point and the removed the limits line. Will make the update. Thanks for noticing!
